#install.packages("tidyverse")
#install.packages("OECD")
#install.packages("lubridate")
library(tidyverse)
library(OECD)
library(lubridate)
revusa <- get_dataset("REVUSA")
revusa <- data.frame(revusa)
df <- subset(revusa, select = -c(TIME_FORMAT))
df <- filter(df, TAX %in% c("TOTALTAX", "1000", "2000", "3000", "4000", "5000", "6000"))
df <- mutate(df, obsTime = year(as.Date(obsTime, "%Y")))
df <- mutate(df, obsValue = as.integer(obsValue))
levelKeys = c("1000" = "Corporate Income Tax", "2000" = "Social Security Tax", "3000"= "Payroll Tax", "4000" = "Property Tax", "5000" = "Taxes on Service and Goods","6000" = "Other Taxes")
df <- mutate(df,TAX=recode(TAX, !!!levelKeys))

#1
ggplot(filter(df, TAX %in% "TOTALTAX"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + facet_grid(vars(GOV)) + labs(title = "US Tax Revenue - Grid")
ggplot(filter(filter(df, TAX %in% "TOTALTAX"), GOV == "FED"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - FED")
ggplot(filter(filter(df, TAX %in% "TOTALTAX"), GOV == "LOCAL"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - LOCAL")
ggplot(filter(filter(df, TAX %in% "TOTALTAX"), GOV == "NES"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - NES")
ggplot(filter(filter(df, TAX %in% "TOTALTAX"), GOV == "SOCSEC"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - SOCSEC")
ggplot(filter(filter(df, TAX %in% "TOTALTAX"), GOV == "STATE"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - STATE")

#2: create multi-line plots (multi-line)
ggplot(filter(df, !TAX %in% "TOTALTAX"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + facet_grid(vars(GOV)) + labs(title = "US Tax Revenue - Grid")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "FED"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - FED")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "LOCAL"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - LOCAL")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "NES"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - NES")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "SOCSEC"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - SOCSEC")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "STATE"), aes(x = obsTime, y = obsValue, color = TAX)) + geom_line() + labs(title = "US Tax Revenue - STATE")

#3: stacked area plot
ggplot(filter(df, !TAX %in% "TOTALTAX"), aes(x = obsTime, y = obsValue, fill = TAX)) + geom_area() + facet_grid(vars(GOV)) + labs(title = "US Tax Revenue - Grid")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "FED"), aes(x = obsTime, y = obsValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - FED")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "LOCAL"), aes(x = obsTime, y = obsValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - LOCAL")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "NES"), aes(x = obsTime, y = obsValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - NES")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "SOCSEC"), aes(x = obsTime, y = obsValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - SOCSEC")
ggplot(filter(filter(df, !TAX %in% "TOTALTAX"), GOV == "STATE"), aes(x = obsTime, y = obsValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - STATE")

#4: proportional stack plot of the data
df_prop <- df %>% spread(TAX, obsValue) %>% gather(key = "TAX", value = "propValue", "Corporate Income Tax", "Social Security Tax", "Payroll Tax", "Property Tax", "Taxes on Service and Goods", "Other Taxes") %>% mutate(propValue = (propValue/TOTALTAX)*100)
ggplot(df_prop, aes(x = obsTime, y = propValue, fill = TAX)) + geom_area() + facet_grid(vars(GOV)) + labs(title = "US Tax Revenue - Grid")
ggplot(filter(df_prop, GOV == "FED"), aes(x = obsTime, y = propValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - FED")
ggplot(filter(df_prop, GOV == "LOCAL"), aes(x = obsTime, y = propValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - LOCAL")
ggplot(filter(df_prop, GOV == "NES"), aes(x = obsTime, y = propValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - NES")
ggplot(filter(df_prop, GOV == "SOCSEC"), aes(x = obsTime, y = propValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - SOCSEC")
ggplot(filter(df_prop, GOV == "STATE"), aes(x = obsTime, y = propValue, fill = TAX)) + geom_area() + labs(title = "US Tax Revenue - STATE")
